plugins {
    id "com.android.application"
}

def keystoreFile =
    System.getenv("ANDROID_KEYSTORE_FILE")

def keystorePassword =
    System.getenv("ANDROID_KEYSTORE_PASSWORD")

def releaseKeyPassword =
    System.getenv("ANDROID_KEY_PASSWORD")

def hasReleaseSigning =
    keystoreFile &&
    keystorePassword &&
    releaseKeyPassword


android {
    namespace "io.unibrij.app"

    compileSdk 36

    defaultConfig {
        applicationId "io.unibrij.app"

        minSdk 23
        targetSdk 36

        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            if (hasReleaseSigning) {
                storeFile file(
                    keystoreFile
                )

                storePassword =
                    keystorePassword

                keyAlias =
                    "unibridge"

                keyPassword =
                    releaseKeyPassword
            }
        }
    }

    buildTypes {
        release {
            if (hasReleaseSigning) {
                signingConfig =
                    signingConfigs.release
            }

            minifyEnabled false
        }
    }
}

dependencies {
    implementation "com.google.androidbrowserhelper:androidbrowserhelper:2.7.3"
}
